version: '3.8'
services:
  backend:
    container_name: app
    build:  
      context: .
      dockerfile: Dockerfile
    command: python main.py
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    depends_on: 
      - db
    networks:
      - internal
      
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: main
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgres
    networks:
      - internal

networks:
  internal:
    driver: bridge