""" 
- schema for data validation
"""
class Validate():
    
    _schema_dw = {
        "type": "object",
        "properties": {
            "first_name": {"type": "string",
                     "minLength":2,
                     "maxLength": 50,
                     "pattern": "^[a-zA-Z\sÑñ]+$"},
            "last_name": {"type": "string",
                     "minLength":2,
                     "maxLength": 50,
                     "pattern": "^[a-zA-Z\sÑñ]+$"},
            "company_name": {"type": "string",
                     "minLength":2,
                     "maxLength": 50,
                     "pattern": "^[a-zA-Z\sÑñ]+$"},
            "address": {"type": "string",
                     "minLength":2,
                     "maxLength": 50,
                     "pattern": "^[a-zA-Z0-9\sÑñ]+$"},
            "city": {"type": "string",
                     "minLength":2,
                     "maxLength": 50,
                     "pattern": "^[a-zA-Z\sÑñ]+$"},
            "state": {"type": "string",
                     "minLength":2,
                     "maxLength": 2,
                     "pattern": "^[a-zA-Z\sÑñ]+$"},
            "zip": {"type": "number"},
            "phone1": {"type": "string",
                     "minLength":2,
                     "maxLength": 20},
            "phone2": {"type": "string",
                     "minLength":2,
                     "maxLength": 20},
            "email": {"type": "string",
                     "minLength":2,
                     "maxLength": 50,
                     },
            "department": {"type": "string",
                     "minLength":2,
                     "maxLength": 50,
                     "pattern": "^[a-zA-Z\sÑñ]+$"},
            },
        "required": ["first_name","last_name","email","phone1"]
    }